### PR TITLE
Create Reusable Content-Text Component #27

### PR DESCRIPTION
**Pull request by preston-56**
:heavy_check_mark: fix: resolved the issues in the different components. I have made brief and descriptive commit messages to explain the changes I have implemented.

### CODE REVIEW

**Comment by LemmyMwaura** [comment]
The changes should be pushed to your previous branch. No need for a new PR. It's easier for me to review that way

**Comment by preston-56** [comment]
@LemmyMwaura I only have one branch. And that's where I have my work pushed

**Comment by LemmyMwaura** [comment]
Closing this as it shouldn't be separate

**Comment by preston-56** [comment]
@LemmyMwaura It's alright. I resolved the previous issues and requested a review.

**Pull request closed without merging**
