### PR TITLE
:art: Create a reusable image container component #19

### PR DESCRIPTION
**Pull request by Leestan360**
# Description

Created an image component for displaying sets of images dynamically. The images I was successful to display with their correct styling and responsiveness include Pill, Window and Card. I had challenges styling the Stacked image container.

The issue related to this PR is issue #19 

Fixes # (19) 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshot (optional)
Pill
Pill

Stacked
stacked

Window
Window

Card
Card

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]

**Comment by LemmyMwaura** [comment]
One Image Config appears to be missing, please add it

**Comment by Leestan360** [comment]
I have added the image config

**Comment by LemmyMwaura** [comment]
@Leestan360 kindly update the screenshot above so i can view it.

**Comment by Leestan360** [comment]
I have added it

**Review by LemmyMwaura — APPROVED** [review]

**Pull request merged**
